.pragma library

var SCALE = 1.0;
var BASE_SCREEN_WIDTH = 1920;
var BASE_SCREEN_HEIGHT = 1080;

var SCREEN_WIDTH = BASE_SCREEN_WIDTH * SCALE;
var SCREEN_HEIGHT = BASE_SCREEN_HEIGHT * SCALE;

var SCREEN_X = 0//-BASE_SCREEN_WIDTH ;
var SCREEN_Y = 0;

var ATTRACT_RIGHT_X = 970;
var ATTRACT_LEFT_X = 750;

var DEBUG_VIEW = false;

var ATTRACT_RANDOM_TIMER = 90000;
